### ISSUE TITLE
DA PHOENIX SUPERHUMAN PROJECT

### ISSUE THREAD

**Issue by PHOENIX19824413** [oracle/oce-react-gallery-sample#2]
https://github.com//qiew/tree/master/first_proto%2Fbak

**Comment by kmacdonaO** [comment]
Hello, this is the second issue you've logged against this repo with no details.  Is there a bug or why have you opened these issues?

**Comment by PHOENIX19824413** [comment]
> Hello, this is the second issue you've logged against this repo with no details.  Is there a bug or why have you opened these issues?

Research
